# Generated by Django 4.0.5 on 2022-12-29 10:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('address', models.TextField(max_length=300, null=True)),
                ('status', models.IntegerField(null=True)),
                ('verification_code', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=5000)),
                ('thumbnail', models.FileField(null=True, upload_to='images')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-update_at', '-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ourTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('facebook', models.CharField(max_length=500, null=True)),
                ('twitter', models.CharField(max_length=500, null=True)),
                ('google', models.CharField(max_length=500, null=True)),
                ('whatapp', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
