# Generated by Django 4.0.5 on 2022-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='description2',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog_model',
            name='description3',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog_model',
            name='description4',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
