# Generated by Django 4.0.5 on 2023-01-04 06:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_model_description2_blog_model_description3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
