# Generated by Django 4.0.5 on 2023-01-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_model_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='blog_model',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='blog_model',
            name='description4',
        ),
    ]
